### ISSUE TITLE
{{content. does not trigger intellisense

### ISSUE THREAD

**Issue by TheWebTech** [williamspiro/HubL-Language-Extension#19]
Idk if I just have a setting wrong but intellisense isn't showing me any suggestions for `content.`
![Gif illustrating problem](https://spin.d.pr/vSFB7X+)

**Comment by TheWebTech** [comment]
hublblog
hubldoc

also doesn't work

basically just a few things do consistently work for me

> 
NOTE: If you are having trouble getting IntelliSense suggestions when in snippet placeholders you may need to add the following to your User Settings "editor.suggest.snippetsPreventQuickSuggestions": false. If parameter suggestions are not showing up, set "editor.parameterHints": true.

I followed this and it didn't work for me

**Comment by TheWebTech** [comment]
I think the problem is specific to my user settings. when I follow your instructions for how to test the extension, in the test enviornment the extension works fine.

**Comment by williamspiro** [comment]
@TheWebTech make sure you have the most recent version of the extension. I was having this same issue from the live extension and updating it fixed it (realized I have 0.0.2)

**Comment by TheWebTech** [comment]
It shows there are no updates after 0.0.2 in the vscode extension manager.

idk if VS code grabs the versions from GitHub automatically or you submit it somewhere, but if it's automatic you probably have to use releases in github to publish versions. It's also kinda just a good practice to do anyways.

**Comment by williamspiro** [comment]
Yea 0.0.5 is the most up to date version https://marketplace.visualstudio.com/items?itemName=WilliamSpiro.hubl you may need to just re-install or something. I will have to look into how they handle updates

**Comment by TheWebTech** [comment]
yeah, manually uninstalling and reinstalling did allow me to update. most of the functionality of the extension is still not working for me :/

**Comment by TheWebTech** [comment]
should maybe create an issue for figuring out auto updating.
